/* Build step. You only need this when you change something in src/.
   1. Type-check the React + TypeScript demo in strict mode.
   2. Bundle it into js/lab.js (the file ui.html loads).
   3. Write js/source-snapshot.js, a copy of every file the source explorer shows. The explorer reads the live files
      when the site is hosted, and falls back to this copy when the page is opened straight from disk.
   Run it with: npm run build */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { build } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const at = (...parts) => join(root, ...parts);

console.log("1/3 Type-checking (strict)...");
execFileSync(
  process.execPath,
  [at("node_modules/typescript/bin/tsc"), "-p", at("src/lab/tsconfig.json")],
  { stdio: "inherit" },
);

console.log("2/3 Bundling src/lab/main.tsx to js/lab.js...");
await build({
  entryPoints: [at("src/lab/main.tsx")],
  outfile: at("js/lab.js"),
  bundle: true,
  format: "iife",
  target: "es2020",
  jsx: "transform",
  jsxFactory: "React.createElement",
  jsxFragment: "React.Fragment",
  minify: true,
  logLevel: "warning",
});
const bundle = readFileSync(at("js/lab.js"), "utf8");
if (/<\/script/i.test(bundle)) throw new Error("js/lab.js contains a closing script tag");

console.log("3/3 Writing js/source-snapshot.js...");
const sandbox = { window: {} };
vm.runInNewContext(readFileSync(at("data/source-files.js"), "utf8"), sandbox);
const snapshot = {};
for (const list of Object.values(sandbox.window.SOURCE_FILES)) {
  for (const path of list) snapshot[path] = readFileSync(at(path), "utf8");
}
writeFileSync(
  at("js/source-snapshot.js"),
  "/* Generated by tools/build.mjs. Do not edit. A copy of the files the source explorer shows. */\nwindow.SOURCE_SNAPSHOT = " +
    JSON.stringify(snapshot).replace(/</g, "\\u003c") +
    ";\n",
);

const kb = (path) => (statSync(at(path)).size / 1024).toFixed(1) + " KB";
console.log(
  `Done. js/lab.js ${kb("js/lab.js")}, js/source-snapshot.js ${kb("js/source-snapshot.js")}`,
);
